changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
  categories:
    - title: Fox Sync
      labels:
        - fox-sync
    - title: Packages And Installation
      labels:
        - installation
        - packaging
        - windows
        - macos
        - linux
    - title: Features And Improvements
      labels:
        - enhancement
    - title: Documentation And Localization
      labels:
        - documentation
        - translation
    - title: Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
