package featurecat.lizzie.search;

import java.util.List;
import java.util.Objects;
import java.util.stream.Stream;

/** Immutable metadata for the functions exposed by offline search. */
public final class FunctionCatalog {
  private static final List<ConfigSettingTarget> CONFIG_SETTING_TARGETS =
      ConfigSettingTargets.all();
  private static final List<String> CATEGORY_KEYS =
      List.of(
          "FunctionSearch.category.file",
          "FunctionSearch.category.analysis",
          "FunctionSearch.category.game",
          "FunctionSearch.category.engine",
          "FunctionSearch.category.sync",
          "FunctionSearch.category.view");
  private static final List<Entry> ENTRIES =
      Stream.concat(
          Stream.of(
          new Entry(
              "weights.download",
              "BottomToolbar.downloadWeight",
              "FunctionSearch.description.weights",
              "FunctionSearch.category.engine",
              TargetType.WINDOW,
              List.of(
                  "Menu.settings",
                  "Menu.autoSetup",
                  "AutoSetup.navWeights",
                  "AutoSetup.officialWeightTab"),
              "",
              "FunctionSearch.aliases.weights",
              "FunctionSearch.weakAliases.weights"),
          new Entry(
              "engine.acceleration",
              "AutoSetup.accelerationTitle",
              "FunctionSearch.description.acceleration",
              "FunctionSearch.category.engine",
              TargetType.WINDOW,
              List.of("Menu.settings", "Menu.autoSetup", "AutoSetup.navAcceleration"),
              "",
              "FunctionSearch.aliases.acceleration",
              "FunctionSearch.weakAliases.acceleration"),
          toolbarEntry(
              "toolbar.change-turn",
              "Menu.btnChangeTurn.toolTipText",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-tools",
              "Menu.btnMarkup.toolTipText",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-letter",
              "Accessibility.markupLetter",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-number",
              "Accessibility.markupNumber",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-cross",
              "Accessibility.markupCross",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-square",
              "Accessibility.markupSquare",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-triangle",
              "Accessibility.markupTriangle",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-eraser",
              "Accessibility.markupEraser",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.markup-clear",
              "Menu.btnMarkupClear.toolTipText",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.painting",
              "Menu.drawPainting.toolTipText",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.force-allow",
              "Menu.selectAllowToolTipText",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.force-avoid",
              "Menu.selectAvoidToolTipText",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.force-clear",
              "Menu.clearSelectToolTipText",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.force-allow-options",
              "Accessibility.allowMoveOptions",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.force-avoid-options",
              "Accessibility.avoidMoveOptions",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.game-pause",
              "Menu.pauseGameBtn",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.game-stop",
              "Menu.endGameBtn",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.game-resign",
              "Menu.resignBtn",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "engine.pda",
              "Accessibility.pdaOptions",
              "FunctionSearch.category.engine",
              TargetType.WINDOW,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.wrn",
              "Menu.chkWRN.toolTopText",
              "FunctionSearch.category.engine",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.time-limit",
              "Menu.chkTime",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.visit-limit",
              "Menu.chkPlayOut",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.analyze-sides",
              "Menu.lblShowAnalyze",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.candidate-sides",
              "Menu.lblShowCandidate",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "toolbar.candidate-info",
              "FunctionSearch.title.toolbar.candidate-info",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "FunctionSearch.path.topToolbar"),
          toolbarEntry(
              "review.previous-ten",
              "Accessibility.previousTenMoves",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "review.next-ten",
              "Accessibility.nextTenMoves",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "review.previous",
              "Accessibility.previousMove",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "review.next",
              "Accessibility.nextMove",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "review.goto",
              "BottomToolbar.gotomove",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "board.try-play",
              "BottomToolbar.tryPlay",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "board.refresh",
              "BottomToolbar.refresh",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "board.delete-without-prompt",
              "BottomToolbar.deleteMove",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.auto-analysis",
              "FunctionSearch.title.legacy.auto-analysis",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.auto-analysis-start",
              "FunctionSearch.title.legacy.auto-analysis-start",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.auto-play",
              "FunctionSearch.title.legacy.auto-play",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.auto-main",
              "BottomToolbar.detail.autoMain",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.auto-sub",
              "BottomToolbar.detail.autoVariation",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.engine-game",
              "FunctionSearch.title.legacy.engine-game",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.engine-game-start",
              "FunctionSearch.title.legacy.engine-game-start",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.engine-game-settings",
              "FunctionSearch.title.legacy.engine-game-settings",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.engine-game-pause",
              "FunctionSearch.title.legacy.engine-game-pause",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "legacy.engine-game-intervene",
              "FunctionSearch.title.legacy.engine-game-intervene",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "share.private-history",
              "BottomToolbar.editHistoryRemote",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "share.public-history",
              "BottomToolbar.shareHistoryRemote",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "FunctionSearch.path.bottomToolbar"),
          toolbarEntry(
              "sync.exit-web-trial",
              "Menu.webBoardForceExitTrial",
              "FunctionSearch.category.sync",
              TargetType.NAVIGATION,
              "FunctionSearch.path.bottomToolbar"),
          menuEntry(
              "menu.showMaxValueReverse",
              "Menu.showMaxValueReverse",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.showMaxValueReverse"),
          boardContext("board.clear-edit-cache", "RightClickMenu.cleanedittemp", false),
          boardContext("board.find-move", "RightClickMenu2.findStone", true),
          boardContext("board.insert-black", "RightClickMenu.addblack", false),
          boardContext("board.insert-white", "RightClickMenu.addwhite", false),
          boardContext("board.allow-point", "RightClickMenu.allow", false),
          boardContext("board.allow-more", "RightClickMenu.allow2", false),
          boardContext("board.allow-remove", "RightClickMenu.allow3", false),
          boardContext("board.avoid-point", "RightClickMenu.avoid", false),
          boardContext("board.keep-forcing", "RightClickMenu.avoid2", false),
          boardContext("board.clear-forcing", "RightClickMenu.cancelavoid", false),
          boardContext("board.track-point", "RightClickMenu.trackPoint", false),
          boardContext("board.untrack-point", "RightClickMenu.untrackPoint", false),
          boardContext("board.clear-tracking", "RightClickMenu.clearAllTracked", false),
          boardContext("board.priority-point", "RightClickMenu.priority", false),
          boardContext("board.clear-priority", "RightClickMenu.clearPriority", false),
          boardContext("board.add-variation", "RightClickMenu.addSuggestionAsBranch", false),
          boardContext("board.move-stone", "RightClickMenu2.moveStone", true),
          boardContext("board.switch-stone", "RightClickMenu2.switchone", true),
          boardContext("board.delete-stone", "RightClickMenu2.deleteone", true),
          boardContext("board.review-stone", "RightClickMenu2.review", true),
          boardContext("board.previous-or-regret", "RightClickMenu.previousMove", false),
          menuEntry(
              "files.new",
              "Menu.newBoard",
              "FunctionSearch.category.file",
              TargetType.NAVIGATION,
              "Menu.fileMenu",
              "Menu.newBoard"),
          menuEntry(
              "files.open",
              "Menu.open",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.open"),
          menuEntry(
              "files.url",
              "Menu.openUrl",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.openUrl"),
          menuEntry(
              "files.save",
              "Menu.save",
              "FunctionSearch.category.file",
              TargetType.NAVIGATION,
              "Menu.fileMenu",
              "Menu.save"),
          menuEntry(
              "files.save-as",
              "Menu.saveAs",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveAs"),
          menuEntry(
              "menu.saveRaw",
              "Menu.saveRaw",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveMore",
              "Menu.saveRaw"),
          menuEntry(
              "menu.saveCommentRaw",
              "Menu.saveCommentRaw",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveMore",
              "Menu.saveCommentRaw"),
          menuEntry(
              "menu.saveBranchRaw",
              "Menu.saveBranchRaw",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveMore",
              "Menu.saveBranchRaw"),
          menuEntry(
              "menu.saveMainBoardScreen",
              "Menu.saveMainBoardScreen",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveMore",
              "Menu.saveMainBoardScreen"),
          menuEntry(
              "menu.saveSubBoardScreen",
              "Menu.saveSubBoardScreen",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveMore",
              "Menu.saveSubBoardScreen"),
          menuEntry(
              "menu.saveWinrate",
              "Menu.saveWinrate",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveMore",
              "Menu.saveWinrate"),
          menuEntry(
              "menu.saveAndLoad",
              "Menu.saveAndLoad",
              "FunctionSearch.category.file",
              TargetType.WINDOW,
              "Menu.fileMenu",
              "Menu.saveAndLoad"),
          menuEntry(
              "menu.copyBoardScreen",
              "Menu.copyBoardScreen",
              "FunctionSearch.category.file",
              TargetType.ACTION,
              "Menu.fileMenu",
              "Menu.copyBoardScreen"),
          menuEntry(
              "menu.copySubBoardScreen",
              "Menu.copySubBoardScreen",
              "FunctionSearch.category.file",
              TargetType.ACTION,
              "Menu.fileMenu",
              "Menu.copySubBoardScreen"),
          menuEntry(
              "menu.copySgf",
              "Menu.copySgf",
              "FunctionSearch.category.file",
              TargetType.ACTION,
              "Menu.fileMenu",
              "Menu.copySgf"),
          menuEntry(
              "menu.pasteSgf",
              "Menu.pasteSgf",
              "FunctionSearch.category.file",
              TargetType.NAVIGATION,
              "Menu.fileMenu",
              "Menu.pasteSgf"),
          menuEntry(
              "menu.loadKomi",
              "Menu.loadKomi",
              "FunctionSearch.category.file",
              TargetType.SETTING,
              "Menu.fileMenu",
              "Menu.loadKomi"),
          menuEntry(
              "menu.forceExit",
              "Menu.forceExit",
              "FunctionSearch.category.file",
              TargetType.NAVIGATION,
              "Menu.fileMenu",
              "Menu.forceExit"),
          menuEntry(
              "menu.exit",
              "Menu.exit",
              "FunctionSearch.category.file",
              TargetType.NAVIGATION,
              "Menu.fileMenu",
              "Menu.exit"),
          menuEntry(
              "menu.mainBoardPos",
              "Menu.mainBoardPos",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainBoardPos"),
          menuEntry(
              "menu.coordsMenu",
              "Menu.coordsMenu",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.coordsMenu"),
          menuEntry(
              "menu.boardStyleMenu",
              "Menu.boardStyle",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.appearanceTheme",
              "Menu.boardStyle"),
          menuEntry(
              "menu.moveMenu",
              "Menu.moveMenu",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.moveMenu"),
          menuEntry(
              "menu.moveRankMenu",
              "Menu.moveRankMenu",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.moveRankMenu"),
          menuEntry(
              "menu.nextMoveHint",
              "Menu.nextMoveHint",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.nextMoveHint"),
          menuEntry(
              "menu.makeAutoPlay",
              "Menu.makeAutoPlay",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.viewMenu",
              "Menu.makeAutoPlay"),
          menuEntry(
              "menu.deletePersistFile",
              "Menu.deletePersistFile",
              "FunctionSearch.category.view",
              TargetType.NAVIGATION,
              "Menu.viewMenu",
              "Menu.deletePersistFile"),
          menuEntry(
              "menu.toggleAppleStyle",
              "Menu.appleStyleUi",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.appearanceTheme",
              "Menu.appleStyleUi"),
          menuEntry(
              "menu.toggleClassicColors",
              "Menu.classicColorTheme",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.appearanceTheme",
              "Menu.classicColorTheme"),
          menuEntry(
              "menu.setCustomBoard",
              "Menu.setCustomBoardBackground",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.appearanceTheme",
              "Menu.setCustomBoardBackground"),
          menuEntry(
              "menu.clearCustomBoard",
              "Menu.clearCustomBoardBackground",
              "FunctionSearch.category.view",
              TargetType.NAVIGATION,
              "Menu.viewMenu",
              "Menu.appearanceTheme",
              "Menu.clearCustomBoardBackground"),
          menuEntry(
              "menu.moveNumberAlwaysFromOne",
              "Menu.moveNumberAlwaysFromOne",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.moveMenu",
              "Menu.moveNumberAlwaysFromOne"),
          menuEntry(
              "menu.moveNumberInBranchFromOne",
              "Menu.moveNumberInBracnhFromOne",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.moveMenu",
              "Menu.moveNumberInBracnhFromOne"),
          menuEntry(
              "menu.showAllMoveNumberInBranch",
              "Menu.showAllMoveNumberInBranch",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.moveMenu",
              "Menu.showAllMoveNumberInBranch"),
          menuEntry(
              "menu.showMoveNumberOnVariationPane",
              "Menu.showMoveNumberOnVariationPane",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.moveMenu",
              "Menu.showMoveNumberOnVariationPane"),
          menuEntry(
              "menu.largeSubBoard",
              "Menu.largeSubBoard",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.largeSubBoard"),
          menuEntry(
              "menu.largeWinrateGraph",
              "Menu.largeWinrateGraph",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.largeWinrateGraph"),
          menuEntry(
              "menu.appendWinrateToComment",
              "Menu.appendWinrateToComment",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.appendWinrateToComment"),
          menuEntry(
              "menu.showNameInBoard",
              "Menu.showNameInBoard",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.showNameInBoard"),
          menuEntry(
              "menu.showCommentConrolPane",
              "Menu.showCommentConrolPane",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.showCommentConrolPane"),
          menuEntry(
              "menu.alwaysOnTop",
              "Menu.alwaysOnTop",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.alwaysOnTop"),
          menuEntry(
              "menu.showNewBoardConfirmDialog",
              "Menu.showNewBoardConfirmDialog",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.showNewBoardConfirmDialog"),
          menuEntry(
              "menu.showReplaceFileConfirmDialog",
              "Menu.showReplaceFileConfirmDialog",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.mainPanelSettings",
              "Menu.showReplaceFileConfirmDialog"),
          menuEntry(
              "menu.suggestion1",
              "Menu.winrate",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.winrate"),
          menuEntry(
              "menu.suggestion2",
              "Menu.visits",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.visits"),
          menuEntry(
              "menu.suggestion3",
              "Menu.scoreLead",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.scoreLead"),
          menuEntry(
              "menu.showScoreAsDiff",
              "Menu.showScoreAsDiff",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.showScoreAsDiff"),
          menuEntry(
              "menu.customInfoOrdr",
              "Menu.customInfoOrdr",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.customInfoOrdr"),
          menuEntry(
              "menu.setCandidatesDelay",
              "Menu.setCandidatesDelay",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.setCandidatesDelay"),
          menuEntry(
              "menu.subboard",
              "Menu.subBoard",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.subBoard"),
          menuEntry(
              "menu.winrateGraph",
              "Menu.winrateGraph",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.winrateGraph"),
          menuEntry(
              "menu.commitPane",
              "Menu.commitPane",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.commitPane"),
          menuEntry(
              "menu.variationPane",
              "Menu.variationPane",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.variationPane"),
          menuEntry(
              "menu.showScrollVariation",
              "Menu.showScrollVariation",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.variationPaneSettings",
              "Menu.showScrollVariation"),
          menuEntry(
              "menu.maxTreeWidth",
              "Menu.maxTreeWidth",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.variationPaneSettings",
              "Menu.maxTreeWidth"),
          menuEntry(
              "menu.ignoreOutOfWidth",
              "Menu.ignoreOutOfWidth",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.variationPaneSettings",
              "Menu.ignoreOutOfWidth"),
          menuEntry(
              "menu.listPane",
              "Menu.listPane",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.listPane"),
          menuEntry(
              "menu.informationPane",
              "Menu.informationPane",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.informationPane"),
          menuEntry(
              "menu.statusPanel",
              "Menu.statusPanel",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.statusPanel"),
          menuEntry(
              "menu.gtpPanel",
              "Menu.gtpPanel",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.gtpPanel"),
          menuEntry(
              "menu.ctrlPanel",
              "Menu.ctrlPanel",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.ctrlPanel"),
          menuEntry(
              "menu.visualizedPanelSettings",
              "Menu.visualizedPanelSettings",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.visualizedPanelSettings"),
          menuEntry(
              "menu.independentMainBoard",
              "Menu.independentMainBoard",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.independentMainBoard"),
          menuEntry(
              "menu.independentMainBoard2",
              "Menu.independentMainBoard2",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.independentMainBoard2"),
          menuEntry(
              "menu.independentSubBoard",
              "Menu.independentSubBoard",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.independentSubBoard"),
          menuEntry(
              "analysis.bad-moves",
              "Menu.hawkEye",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.hawkEye"),
          menuEntry(
              "menu.SuggestionList",
              "Menu.SuggestionList",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.SuggestionList"),
          menuEntry(
              "menu.restoreDefaultPanelSizes",
              "Menu.restoreDefaultPanelSizes",
              "FunctionSearch.category.view",
              TargetType.NAVIGATION,
              "Menu.viewMenu",
              "Menu.panel",
              "Menu.restoreDefaultPanelSizes"),
          menuEntry(
              "menu.showSuggestionOrder",
              "Menu.showSuggestionOrder",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.showSuggestionOrder"),
          menuEntry(
              "menu.showWhiteSuggestWhite",
              "Menu.showWhiteSuggestWhite",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.showWhiteSuggestWhite"),
          menuEntry(
              "menu.showVariationOnMouse",
              "Menu.showVariationOnMouse",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.showVariationOnMouse"),
          menuEntry(
              "menu.noRefreshOnMouse",
              "Menu.noRefreshOnMouse",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.noRefreshOnMouse"),
          menuEntry(
              "menu.showWinRateOrScoreLeadLine",
              "Menu.showWinRateOrScoreLeadLine",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.winrateGraphSettings",
              "Menu.showWinRateOrScoreLeadLine"),
          menuEntry(
              "menu.showWinrateGraphFill",
              "Menu.showWinrateGraphFill",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.winrateGraphSettings",
              "Menu.showWinrateGraphFill"),
          menuEntry(
              "menu.showBlunderBar",
              "Menu.showBlunderBar",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.winrateGraphSettings",
              "Menu.showBlunderBar"),
          menuEntry(
              "menu.showMouseOverWinrateGraph",
              "Menu.showMouseOverWinrateGraph",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.winrateGraphSettings",
              "Menu.showMouseOverWinrateGraph"),
          menuEntry(
              "menu.initialMaxScoreLead",
              "Menu.initialMaxScoreLead",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.winrateGraphSettings",
              "Menu.initialMaxScoreLead"),
          menuEntry(
              "menu.setReplayInterval",
              "Menu.setReplayInterval",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.Suggestions",
              "Menu.setReplayInterval"),
          menuEntry(
              "menu.heatMapSettings",
              "Menu.heatMapSettings",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.subBoardSettings",
              "Menu.heatMapSettings"),
          menuEntry(
              "menu.subBoardShowVar",
              "Menu.subBoardShowVar",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.subBoardSettings",
              "Menu.subBoardShowVar"),
          menuEntry(
              "menu.layoutModeMenu",
              "Menu.layoutMode",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.layoutMode"),
          menuEntry(
              "menu.independentBoardMode",
              "Menu.independentBoardMode",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.independentBoardMode"),
          menuEntry(
              "menu.kataScolreLead",
              "Menu.kataScolreLead",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.kataSettings",
              "Menu.kataScolreLead"),
          menuEntry(
              "menu.kataEstimate",
              "Menu.kataEstimate",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.kataSettings",
              "Menu.kataEstimate"),
          menuEntry(
              "menu.kataEstimateSaveState",
              "Menu.kataEstimateSaveState",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.kataSettings",
              "Menu.kataEstimate",
              "Menu.kataEstimateSaveState"),
          menuEntry(
              "menu.kataEstimateByTransparentSmall",
              "Menu.kataEstimateByTransparentSmall",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.kataSettings",
              "Menu.kataEstimate",
              "Menu.kataEstimateByTransparentSmall"),
          menuEntry(
              "menu.kataEstimateInPureNet",
              "Menu.kataEstimateInPureNet",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.kataSettings",
              "Menu.kataEstimate",
              "Menu.kataEstimateInPureNet"),
          menuEntry(
              "menu.useMovesOwnership",
              "Menu.useMovesOwnership",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.kataSettings",
              "Menu.kataEstimate",
              "Menu.useMovesOwnership"),
          menuEntry(
              "menu.useKataEstimateShortcut",
              "Menu.useKataEstimateShortcut",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.kataSettings",
              "Menu.kataEstimate",
              "Menu.useKataEstimateShortcut"),
          menuEntry(
              "menu.continueGameAgainstAi",
              "Menu.continueGameAgainstAi",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.continueGameAgainstAi"),
          menuEntry(
              "menu.newGenmoveGame",
              "Menu.newGenmoveGame",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.game",
              "Menu.newGame",
              "Menu.newGenmoveGame"),
          menuEntry(
              "menu.newEngineGame",
              "Menu.newEngineGame",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.game",
              "Menu.newGame",
              "Menu.newEngineGame"),
          menuEntry(
              "menu.newHumanSlGame",
              "Menu.newHumanSlGame",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.game",
              "Menu.newGame",
              "Menu.newHumanSlGame"),
          menuEntry(
              "menu.scoreGame",
              "Menu.scoreGame",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.game",
              "Menu.scoreGame"),
          menuEntry(
              "menu.setAiTime",
              "Menu.setAiTime",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.game",
              "Menu.setAiTime"),
          menuEntry(
              "game.stop-human",
              "Menu.breakGame",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.breakGame"),
          menuEntry(
              "menu.breakEngineGame",
              "Menu.breakEngineGame",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.breakEngineGame"),
          menuEntry(
              "menu.pauseEngineGame",
              "Menu.pauseEngineGame",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.game",
              "Menu.pauseEngineGame"),
          menuEntry(
              "menu.changeEngineGameNumbers",
              "Menu.changeEngineGameNumbers",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.game",
              "Menu.changeEngineGameNumbers"),
          menuEntry(
              "menu.intervention",
              "Menu.intervention",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.game",
              "Menu.intervention"),
          menuEntry(
              "menu.playBestMove",
              "Menu.playBestMove",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.playBestMove"),
          menuEntry(
              "menu.playPassMove",
              "Menu.playPassMove",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.playPassMove"),
          menuEntry(
              "menu.setupModeToggle",
              "Menu.setupModeToggle",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.setupModeToggle"),
          menuEntry(
              "menu.setupClearAll",
              "Menu.setupClearAll",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.setupClearAll"),
          menuEntry(
              "menu.setupBlackToPlay",
              "Menu.setupBlackToPlay",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.setupBlackToPlay"),
          menuEntry(
              "menu.setupWhiteToPlay",
              "Menu.setupWhiteToPlay",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.setupWhiteToPlay"),
          menuEntry(
              "menu.convertCurrentPosition",
              "Menu.convertCurrentPositionToStartingPosition",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.convertCurrentPositionToStartingPosition"),
          menuEntry(
              "menu.continueLadder",
              "Menu.game.continueLadder",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.game",
              "Menu.game.continueLadder"),
          menuEntry(
              "analysis.toggle",
              "Menu.togglePonder",
              "FunctionSearch.category.analysis",
              TargetType.ACTION,
              "Menu.analyze",
              "Menu.togglePonder"),
          menuEntry(
              "analysis.commentary",
              "Menu.aiCommentary",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.aiCommentary"),
          menuEntry(
              "game.tsumego",
              "Menu.tsumeGo",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.tsumeGo"),
          menuEntry(
              "menu.captureTsumeGo",
              "Menu.captureTsumeGo",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.captureTsumeGo"),
          menuEntry(
              "auto-analysis",
              "Menu.autoAnalyze",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.autoAnalyze"),
          menuEntry(
              "batch-analysis",
              "Menu.batchAnalyze",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.batchAnalyze"),
          menuEntry(
              "batch-deep-analysis",
              "Menu.batchAnalysisMode",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.batchAnalysisMode"),
          menuEntry(
              "stop-analysis",
              "Menu.stopAutoAnalyze",
              "FunctionSearch.category.analysis",
              TargetType.ACTION,
              "Menu.analyze",
              "Menu.stopAutoAnalyze"),
          menuEntry(
              "batch-progress",
              "Menu.batchAnalyzeTable",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.batchAnalyzeTable"),
          menuEntry(
              "partial-lightning-analysis",
              "Menu.flashAnalyzePartGame",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.flashAnalyzePartGame"),
          menuEntry(
              "all-branches-lightning-analysis",
              "Menu.flashAnalyzeAllBranches",
              "FunctionSearch.category.analysis",
              TargetType.ACTION,
              "Menu.analyze",
              "Menu.flashAnalyzeAllBranches"),
          menuEntry(
              "lightning-analysis-settings",
              "Menu.flashAnalyzeSettings",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.flashAnalyzeSettings"),
          menuEntry(
              "menu.playerStrengthEstimate",
              "Menu.playerStrengthEstimate",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.playerStrengthEstimate"),
          menuEntry(
              "menu.showHeatmap",
              "Menu.showHeatmap",
              "FunctionSearch.category.analysis",
              TargetType.ACTION,
              "Menu.analyze",
              "Menu.showHeatmap"),
          menuEntry(
              "menu.showPolicy",
              "Menu.showPolicy",
              "FunctionSearch.category.analysis",
              TargetType.SETTING,
              "Menu.analyze",
              "Menu.showPolicy"),
          menuEntry(
              "menu.clearAllLizzieCache",
              "Menu.clearAllLizzieCache",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "Menu.analyze",
              "Menu.clearAllLizzieCache"),
          menuEntry(
              "menu.clearThisLizzieCache",
              "Menu.clearThisLizzieCache",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "Menu.analyze",
              "Menu.clearThisLizzieCache"),
          menuEntry(
              "menu.clearAllLizzieBestmoves",
              "Menu.clearAllLizzieBestmoves",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "Menu.analyze",
              "Menu.clearAllLizzieBestmoves"),
          menuEntry(
              "menu.clearThisLizzieBestmoves",
              "Menu.clearThisLizzieBestmoves",
              "FunctionSearch.category.analysis",
              TargetType.NAVIGATION,
              "Menu.analyze",
              "Menu.clearThisLizzieBestmoves"),
          menuEntry(
              "menu.addBlack",
              "Menu.addBlack",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.addBlack"),
          menuEntry(
              "menu.addWhite",
              "Menu.addWhite",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.addWhite"),
          menuEntry(
              "menu.alternatelyMoves",
              "Menu.alternatelyMoves",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.alternatelyMoves"),
          menuEntry(
              "menu.allowDoubleClick",
              "Menu.allowDoubleClick",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.edit",
              "Menu.allowDoubleClick"),
          menuEntry(
              "menu.allowDrag",
              "Menu.allowDrag",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.edit",
              "Menu.allowDrag"),
          menuEntry(
              "menu.allowClickReview",
              "Menu.allowClickReview",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.edit",
              "Menu.allowClickReview"),
          menuEntry(
              "menu.insertBlack",
              "Menu.insertBlack",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.edit",
              "Menu.insertBlack"),
          menuEntry(
              "menu.insertWhite",
              "Menu.insertWhite",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.edit",
              "Menu.insertWhite"),
          menuEntry(
              "menu.clearBoard",
              "Menu.clearBoard",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.clearBoard"),
          menuEntry(
              "menu.backToMainBranch",
              "Menu.backToMainBranch",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.edit",
              "Menu.backToMainBranch"),
          menuEntry(
              "menu.setAsMain",
              "Menu.setAsMain",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.setAsMain"),
          menuEntry(
              "menu.jumpToFirst",
              "Menu.jumpToFirst",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.edit",
              "Menu.jumpToFirst"),
          menuEntry(
              "menu.jumpToLast",
              "Menu.jumpToLast",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.edit",
              "Menu.jumpToLast"),
          menuEntry(
              "menu.jumpToLeft",
              "Menu.jumpToLeft",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.edit",
              "Menu.jumpToLeft"),
          menuEntry(
              "menu.jumpToRight",
              "Menu.jumpToRight",
              "FunctionSearch.category.game",
              TargetType.ACTION,
              "Menu.edit",
              "Menu.jumpToRight"),
          menuEntry(
              "menu.delete",
              "Menu.delete",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.delete"),
          menuEntry(
              "menu.deleteBranch",
              "Menu.deleteBranch",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.deleteBranch"),
          menuEntry(
              "menu.undoDelete",
              "Menu.undoDelete",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.undoDelete"),
          menuEntry(
              "menu.redoDelete",
              "Menu.redoDelete",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.redoDelete"),
          menuEntry(
              "game.komi",
              "Menu.setInfo",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.edit",
              "Menu.setInfo",
              "GameInfoDialog.komi"),
          menuEntry(
              "menu.setBoard",
              "Menu.setBoard",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.edit",
              "Menu.setBoard"),
          menuEntry(
              "menu.exchange",
              "Menu.exchange",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.exchange"),
          menuEntry(
              "menu.spinRight",
              "Menu.spinRight",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.spinRight"),
          menuEntry(
              "menu.spinLeft",
              "Menu.spinLeft",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.spinLeft"),
          menuEntry(
              "menu.mirrorVertical",
              "Menu.mirrorVertical",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.mirrorVertical"),
          menuEntry(
              "menu.mirrorHorizon",
              "Menu.mirrorHorizon",
              "FunctionSearch.category.game",
              TargetType.NAVIGATION,
              "Menu.edit",
              "Menu.mirrorHorizon"),
          menuEntry(
              "menu.yikeLive",
              "Menu.yikeLive",
              "FunctionSearch.category.sync",
              TargetType.WINDOW,
              "Menu.sync",
              "Menu.yikeLive"),
          menuEntry(
              "menu.yikeLiveWeb",
              "Menu.yikeLiveWeb",
              "FunctionSearch.category.sync",
              TargetType.WINDOW,
              "Menu.sync",
              "Menu.yikeLiveWeb"),
          menuEntry(
              "menu.yikeRoom",
              "Menu.yikeRoom",
              "FunctionSearch.category.sync",
              TargetType.WINDOW,
              "Menu.sync",
              "Menu.yikeRoom"),
          menuEntry(
              "menu.foxKifu",
              "Menu.foxKifu",
              "FunctionSearch.category.sync",
              TargetType.WINDOW,
              "Menu.sync",
              "Menu.foxKifu"),
          menuEntry(
              "menu.tencentKifu",
              "Menu.tencentKifu",
              "FunctionSearch.category.sync",
              TargetType.WINDOW,
              "Menu.sync",
              "Menu.tencentKifu"),
          menuEntry(
              "sync.board",
              "Menu.readBoard",
              "FunctionSearch.category.sync",
              TargetType.WINDOW,
              "Menu.sync",
              "Menu.readBoard"),
          menuEntry(
              "menu.webBoardToggle",
              "Menu.webBoardStart",
              "FunctionSearch.category.sync",
              TargetType.ACTION,
              "Menu.sync",
              "Menu.webBoard",
              "Menu.webBoardStart"),
          menuEntry(
              "menu.webBoardCopyUrl",
              "Menu.webBoardCopyUrl",
              "FunctionSearch.category.sync",
              TargetType.ACTION,
              "Menu.sync",
              "Menu.webBoard",
              "Menu.webBoardCopyUrl"),
          menuEntry(
              "menu.EnableEnterYikeGame",
              "Menu.EnableEnterYikeGame",
              "FunctionSearch.category.sync",
              TargetType.SETTING,
              "Menu.sync",
              "Menu.EnableEnterYikeGame"),
          menuEntry(
              "menu.alwaysGoToLastMove",
              "Menu.alwaysGoToLastMove",
              "FunctionSearch.category.sync",
              TargetType.SETTING,
              "Menu.sync",
              "Menu.alwaysGoToLastMove"),
          menuEntry(
              "sync.settings",
              "Menu.readBoardSettings",
              "FunctionSearch.category.sync",
              TargetType.SETTING,
              "Menu.sync",
              "Menu.readBoardSettings"),
          menuEntry(
              "menu.alwaysKeepBoardStatSync",
              "Menu.alwaysKeepBoardStatSync",
              "FunctionSearch.category.sync",
              TargetType.SETTING,
              "Menu.sync",
              "Menu.readBoardSettings",
              "Menu.alwaysKeepBoardStatSync"),
          menuEntry(
              "menu.readBoardGetFocus",
              "Menu.readBoardGetFocus",
              "FunctionSearch.category.sync",
              TargetType.SETTING,
              "Menu.sync",
              "Menu.readBoardSettings",
              "Menu.readBoardGetFocus"),
          menuEntry(
              "menu.topToolBar",
              "Menu.topToolBar",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.toolbar",
              "Menu.topToolBar"),
          menuEntry(
              "menu.autoWrap",
              "Menu.autoWrap",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.toolbar",
              "Menu.topToolBar",
              "Menu.autoWrap"),
          menuEntry(
              "menu.bottomToolBar",
              "Menu.bottomToolBar",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.toolbar",
              "Menu.bottomToolBar"),
          menuEntry(
              "menu.customTopToolBar",
              "Menu.customToolbar",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.toolbar",
              "Menu.topToolBar",
              "Menu.customToolbar"),
          menuEntry(
              "menu.customToolbarItem",
              "Menu.customToolbar",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.toolbar",
              "Menu.bottomToolBar",
              "Menu.customToolbar"),
          menuEntry(
              "menu.diagnosticsAndLogs",
              "Menu.diagnosticsAndLogs",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.help",
              "Menu.diagnosticsAndLogs"),
          menuEntry(
              "menu.stopFullTrace",
              "Menu.stopFullTrace",
              "FunctionSearch.category.view",
              TargetType.ACTION,
              "Menu.help",
              "Menu.stopFullTrace"),
          menuEntry(
              "menu.about",
              "Menu.about",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.help",
              "Menu.about"),
          menuEntry(
              "menu.checkUpdate",
              "Menu.checkUpdate",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.help",
              "Menu.checkUpdate"),
          menuEntry(
              "menu.clearUserData",
              "Menu.clearAllPersonalData",
              "FunctionSearch.category.view",
              TargetType.NAVIGATION,
              "Menu.help",
              "Menu.clearAllPersonalData"),
          menuEntry(
              "engine.configuration",
              "Menu.engineConfig",
              "FunctionSearch.category.engine",
              TargetType.WINDOW,
              "Menu.settings",
              "Menu.engineConfig"),
          menuEntry(
              "engine.remote",
              "Menu.remoteCompute",
              "FunctionSearch.category.engine",
              TargetType.WINDOW,
              "Menu.settings",
              "Menu.remoteCompute"),
          menuEntry(
              "engine.rules",
              "Menu.engineRules",
              "FunctionSearch.category.engine",
              TargetType.SETTING,
              "Menu.settings",
              "Menu.engineRules",
              "SetKataRules.lblScoringRule"),
          menuEntry(
              "engine.parameters",
              "Menu.engineParameters",
              "FunctionSearch.category.engine",
              TargetType.WINDOW,
              "Menu.settings",
              "Menu.engineParameters"),
          menuEntry(
              "menu.initSettings",
              "Menu.initSettings",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.settings",
              "Menu.initSettings"),
          menuEntry(
              "engine.setup",
              "Menu.autoSetup",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.settings",
              "Menu.autoSetup"),
          menuEntry(
              "settings.general",
              "Menu.comprehensiveSettings",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.settings",
              "Menu.comprehensiveSettings"),
          menuEntry(
              "menu.theme",
              "Menu.theme",
              "FunctionSearch.category.view",
              TargetType.WINDOW,
              "Menu.settings",
              "Menu.theme"),
          menuEntry(
              "menu.language",
              "menu.language",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.settings",
              "menu.language"),
          menuEntry(
              "menu.frameFontSize",
              "menu.frameFontSize",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.settings",
              "menu.frameFontSize"),
          menuEntry(
              "menu.frameLooks",
              "menu.frameLooks",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.settings",
              "menu.frameLooks"),
          menuEntry(
              "menu.playSound",
              "Menu.playSound",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.settings",
              "Menu.playSound"),
          menuEntry(
              "menu.notPlaySoundInSync",
              "Menu.notPlaySoundInSync",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.settings",
              "Menu.notPlaySoundInSync"),
          menuEntry(
              "menu.showContribute",
              "Menu.showContribute",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.settings",
              "Menu.showContribute"),
          menuEntry(
              "menu.kataGoDistributedTraining",
              "Menu.kataGoDistributedTraining",
              "FunctionSearch.category.engine",
              TargetType.ACTION,
              "Menu.contributeMenu",
              "Menu.kataGoDistributedTraining"),
          menuEntry(
              "menu.kataGoTrainingSettings",
              "Menu.kataGoTrainingSettings",
              "FunctionSearch.category.engine",
              TargetType.WINDOW,
              "Menu.contributeMenu",
              "Menu.kataGoTrainingSettings"),
          menuEntry(
              "menu.kataGoOfficialWebsite",
              "Menu.kataGoOfficialWebsite",
              "FunctionSearch.category.engine",
              TargetType.ACTION,
              "Menu.contributeMenu",
              "Menu.kataGoOfficialWebsite"),
          menuEntry(
              "files.recent",
              "Menu.openRecent",
              "FunctionSearch.category.file",
              TargetType.NAVIGATION,
              "Menu.fileMenu",
              "Menu.openRecent"),
          menuEntry(
              "menu.minPlayoutsForNextMove",
              "Menu.minPlayoutsForNextMove",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.nextMoveHint",
              "Menu.minPlayoutsForNextMove"),
          menuEntry(
              "tools.quick-start",
              "Menu.quickLinks",
              "FunctionSearch.category.view",
              TargetType.NAVIGATION,
              "Menu.quickLinks"),
          menuEntry(
              "engine.select",
              "FunctionSearch.title.engine.select",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select"),
          menuEntry(
              "engine.select-secondary",
              "FunctionSearch.title.engine.select-secondary",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select-secondary"),
          menuEntry(
              "game.ai-coach",
              "Menu.aiCoach",
              "FunctionSearch.category.engine",
              TargetType.ACTION,
              "Menu.aiCoach"),
          menuEntry(
              "menu.restartCurrentEngine",
              "Menu.restartCurrentEngine",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select",
              "Menu.restartCurrentEngine"),
          menuEntry(
              "menu.shutdownCurrentEngine",
              "Menu.shutdownCurrentEngine",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select",
              "Menu.shutdownEngine",
              "Menu.shutdownCurrentEngine"),
          menuEntry(
              "menu.shutdownOtherEngine",
              "Menu.shutdownOtherEngine",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select",
              "Menu.shutdownEngine",
              "Menu.shutdownOtherEngine"),
          menuEntry(
              "menu.shutdownAllEngine",
              "Menu.shutdownAllEngine",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select",
              "Menu.shutdownEngine",
              "Menu.shutdownAllEngine"),
          menuEntry(
              "menu.restartCurrentEngine2",
              "Menu.restartCurrentEngine",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select-secondary",
              "Menu.restartCurrentEngine"),
          menuEntry(
              "menu.shutdownCurrentEngine2",
              "Menu.shutdownCurrentEngine",
              "FunctionSearch.category.engine",
              TargetType.NAVIGATION,
              "FunctionSearch.title.engine.select-secondary",
              "Menu.shutdownCurrentEngine"),
          menuEntry(
              "whole-game-deep-analysis",
              "Menu.wholeGameDeepAnalysis",
              "FunctionSearch.category.analysis",
              TargetType.WINDOW,
              "Menu.analyze",
              "Menu.wholeGameDeepAnalysis"),
          menuEntry(
              "whole-game-lightning-overview",
              "Menu.flashAnalyzeAllGame",
              "FunctionSearch.category.analysis",
              TargetType.ACTION,
              "Menu.analyze",
              "Menu.flashAnalyzeAllGame"),
          menuEntry(
              "menu.newAnalyzeModeGame",
              "Menu.newAnalyzeModeGame",
              "FunctionSearch.category.game",
              TargetType.WINDOW,
              "Menu.game",
              "Menu.newGame",
              "Menu.newAnalyzeModeGame"),
          menuEntry(
              "menu.setupToolBlack",
              "Menu.setupToolBlack",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.setupToolBlack"),
          menuEntry(
              "menu.setupToolWhite",
              "Menu.setupToolWhite",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.setupToolWhite"),
          menuEntry(
              "menu.setupToolErase",
              "Menu.setupToolErase",
              "FunctionSearch.category.game",
              TargetType.SETTING,
              "Menu.game",
              "Menu.startingPositionSetup",
              "Menu.setupToolErase"),
          menuEntry(
              "menu.custom-layout-1",
              "FunctionSearch.title.custom-layout-1",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "FunctionSearch.title.custom-layout-1"),
          menuEntry(
              "menu.custom-layout-2",
              "FunctionSearch.title.custom-layout-2",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "FunctionSearch.title.custom-layout-2"),
          menuEntry(
              "toolbar.detailed",
              "FunctionSearch.title.detailed-toolbar",
              "FunctionSearch.category.view",
              TargetType.SETTING,
              "Menu.viewMenu",
              "Menu.toolbar",
              "Menu.bottomToolBar",
              "FunctionSearch.title.detailed-toolbar")),
          CONFIG_SETTING_TARGETS.stream().map(ConfigSettingTarget::entry))
      .toList();

  private FunctionCatalog() {}

  private static Entry menuEntry(
      String id, String titleKey, String categoryKey, TargetType type, String... pathKeys) {
    return new Entry(
        id,
        titleKey,
        "FunctionSearch.description." + id,
        categoryKey,
        type,
        List.of(pathKeys),
        shortcut(id),
        "FunctionSearch.aliases." + id,
        "");
  }

  private static Entry toolbarEntry(
      String id, String titleKey, String categoryKey, TargetType type, String pathKey) {
    return new Entry(
        id,
        titleKey,
        "FunctionSearch.description." + id,
        categoryKey,
        type,
        List.of(pathKey, titleKey),
        shortcut(id),
        "FunctionSearch.aliases." + id,
        "");
  }

  private static Entry boardContext(String id, String titleKey, boolean occupied) {
    return new Entry(
        id,
        titleKey,
        "FunctionSearch.description." + id,
        "FunctionSearch.category.game",
        TargetType.CONTEXT,
        List.of(
            "FunctionSearch.path.board",
            occupied ? "FunctionSearch.path.occupied" : "FunctionSearch.path.emptyPoint",
            titleKey),
        "",
        "FunctionSearch.aliases." + id,
        "");
  }

  private static String shortcut(String id) {
    return switch (id) {
      case "files.open" -> "O";
      case "files.save" -> "Ctrl+S";
      case "files.save-as" -> "S";
      case "menu.saveRaw" -> "Ctrl+Shift+S";
      case "menu.saveBranchRaw" -> "Ctrl+Alt+S";
      case "menu.saveMainBoardScreen" -> "Alt+S";
      case "menu.saveSubBoardScreen" -> "Shift+S";
      case "menu.saveWinrate" -> "Alt+Shift+S";
      case "sync.board" -> "Alt+O";
      case "menu.yikeLive" -> "Shift+O";
      case "menu.newGenmoveGame" -> "N";
      case "menu.newAnalyzeModeGame" -> "Alt+N";
      case "analysis.toggle" -> "Space";
      case "analysis.bad-moves" -> "Y";
      case "game.komi" -> "I";
      case "menu.setBoard" -> "Ctrl+I";
      case "menu.setAsMain" -> "L";
      case "menu.playPassMove" -> "P";
      case "menu.jumpToFirst" -> "Home";
      case "menu.jumpToLast" -> "End";
      case "menu.copySgf" -> "Ctrl+C";
      case "menu.pasteSgf" -> "Ctrl+V";
      case "menu.makeAutoPlay" -> "Ctrl+A";
      case "auto-analysis" -> "A";
      case "whole-game-deep-analysis" -> "Ctrl+Shift+B";
      case "whole-game-lightning-overview" -> "Ctrl+B";
      case "game.stop-human" -> "Space";
      case "engine.parameters" -> "Alt+D";
      default -> "";
    };
  }

  public static Entry entry(String id) {
    for (Entry entry : ENTRIES) {
      if (entry.id().equals(id)) return entry;
    }
    return null;
  }

  /** Returns the immutable production catalog. */
  public static List<Entry> entries() {
    return ENTRIES;
  }

  /** Canonical browse categories in their UI order. */
  public static List<String> categoryKeys() {
    return CATEGORY_KEYS;
  }

  /** Visible editable rows in the comprehensive settings dialog. */
  public static List<ConfigSettingTarget> configSettingTargets() {
    return CONFIG_SETTING_TARGETS;
  }

  public static ConfigSettingTarget configSettingTarget(String id) {
    for (ConfigSettingTarget target : CONFIG_SETTING_TARGETS) {
      if (target.id().equals(id)) return target;
    }
    return null;
  }

  public static List<ConfigSettingTarget> configSettingTargets(SettingSection section) {
    return CONFIG_SETTING_TARGETS.stream().filter(target -> target.section() == section).toList();
  }

  /** Comprehensive-settings destinations; the section selects the rebuilt page owner. */
  public record ConfigSettingTarget(
      String id,
      SettingSection section,
      String titleKey,
      String descriptionKey,
      String categoryKey,
      String strongAliasesKey,
      String weakAliasesKey) {
    public ConfigSettingTarget(
        String id,
        SettingSection section,
        String titleKey,
        String descriptionKey,
        String categoryKey) {
      this(id, section, titleKey, descriptionKey, categoryKey, "", "");
    }

    public ConfigSettingTarget {
      id = Objects.requireNonNull(id, "id");
      section = Objects.requireNonNull(section, "section");
      titleKey = Objects.requireNonNull(titleKey, "titleKey");
      descriptionKey = Objects.requireNonNull(descriptionKey, "descriptionKey");
      categoryKey = Objects.requireNonNull(categoryKey, "categoryKey");
      strongAliasesKey = strongAliasesKey == null ? "" : strongAliasesKey;
      weakAliasesKey = weakAliasesKey == null ? "" : weakAliasesKey;
    }

    private Entry entry() {
      return new Entry(
          id,
          titleKey,
          descriptionKey,
          categoryKey,
          TargetType.SETTING,
          List.of("Menu.settings", "Menu.comprehensiveSettings", section.pathKey(), titleKey),
          "",
          strongAliasesKey,
          weakAliasesKey);
    }
  }

  public enum SettingSection {
    DISPLAY("ConfigDialog2.modern.nav.display"),
    KIFU("ConfigDialog2.modern.nav.kifu"),
    ENGINE("ConfigDialog2.modern.nav.engine"),
    PLAY("ConfigDialog2.modern.nav.play"),
    ADVANCED("ConfigDialog2.modern.nav.advanced"),
    THEME("ConfigDialog2.modern.nav.theme");

    private final String pathKey;

    SettingSection(String pathKey) {
      this.pathKey = pathKey;
    }

    public String pathKey() {
      return pathKey;
    }
  }

  /** The kind of destination owned by a catalog entry. */
  public enum TargetType {
    WINDOW,
    SETTING,
    ACTION,
    NAVIGATION,
    CONTEXT
  }

  /** Stable function metadata; all collection state is defensively immutable. */
  public record Entry(
      String id,
      String titleKey,
      String descriptionKey,
      String categoryKey,
      TargetType targetType,
      List<String> pathKeys,
      String shortcut,
      String strongAliasesKey,
      String weakAliasesKey) {
    public Entry {
      id = requireText(id, "id");
      titleKey = requireText(titleKey, "titleKey");
      descriptionKey = requireText(descriptionKey, "descriptionKey");
      categoryKey = requireText(categoryKey, "categoryKey");
      targetType = Objects.requireNonNull(targetType, "targetType");
      pathKeys = pathKeys == null ? List.of() : List.copyOf(pathKeys);
      shortcut = shortcut == null ? "" : shortcut;
      strongAliasesKey = strongAliasesKey == null ? "" : strongAliasesKey;
      weakAliasesKey = weakAliasesKey == null ? "" : weakAliasesKey;
    }

    private static String requireText(String value, String field) {
      return Objects.requireNonNull(value, field);
    }
  }
}
